insert into typ_choroby values(1,'Alergie');
insert into typ_choroby values(2,'Civilizačné choroby');
insert into typ_choroby values(3,'Dedičné choroby');
insert into typ_choroby values(4,'Duševné poruchy');
insert into typ_choroby values(5,'Fóbie');
insert into typ_choroby values(6,'Choroby detí');
insert into typ_choroby values(7,'Choroby dolných končatín');
insert into typ_choroby values(8,'Choroby dýchacej sústavy');
insert into typ_choroby values(9,'Choroby hrudníka');
insert into typ_choroby values(10,'Choroby hypofýzy');
insert into typ_choroby values(11,'Choroby kostí a kĺbov');
insert into typ_choroby values(12,'Choroby kože');
insert into typ_choroby values(13,'Choroby krvi a krvotvorných orgánov');
insert into typ_choroby values(14,'Choroby močovej a pohlavnej sústavy');
insert into typ_choroby values(15,'Choroby mozgu');
insert into typ_choroby values(16,'Choroby obehovej sústavy');
insert into typ_choroby values(17,'Choroby obličiek');
insert into typ_choroby values(18,'Choroby oka');
insert into typ_choroby values(19,'Choroby tráviacej sústavy');
insert into typ_choroby values(20,'Choroby ucha a hlávkového výbežku');
insert into typ_choroby values(21,'Infekčné choroby');
insert into typ_choroby values(22,'Nádory');
insert into typ_choroby values(23,'Neurologické choroby');
insert into typ_choroby values(24,'Pohlavné choroby');
insert into typ_choroby values(25,'Poruchy príjmu potravy');
insert into typ_choroby values(26,'Psychózy');
insert into typ_choroby values(27,'Závislosti');
