
 CREATE DATABASE LINK "DB_LINK_VYPLATY.FRI.UNIZA.SK"
   CONNECT TO "LABAT2" IDENTIFIED BY VALUES ':1'
   USING '(DESCRIPTION=
    (ADDRESS=
     (PROTOCOL=TCP)
     (HOST=asterix.fri.uniza.sk)
     (PORT=1521))
    (CONNECT_DATA=
     (SERVICE_NAME=orcl.fri.uniza.sk)))';

