insert into okres values('609', 'Rimavská Sobota', 'BC');
insert into okres values('202', 'Galanta', 'TA');
insert into okres values('701', 'Bardejov', 'PV');
insert into okres values('703', 'Kežmarok', 'PV');
insert into okres values('509', 'Turčianske Teplice', 'ZI');
insert into okres values('707', 'Prešov', 'PV');
insert into okres values('309', 'Trenčín', 'TC');
insert into okres values('702', 'Humenné', 'PV');
insert into okres values('403', 'Nitra', 'NI');
insert into okres values('404', 'Nové Zámky', 'NI');
insert into okres values('406', 'Topoľčany', 'NI');
insert into okres values('808', 'Rožňava', 'KI');
insert into okres values('810', 'Spišská Nová Ves', 'KI');
insert into okres values('713', 'Vranov nad Topľou', 'PV');
insert into okres values('507', 'Námestovo', 'ZI');
insert into okres values('611', 'Zvolen', 'BC');
insert into okres values('603', 'Brezno', 'BC');
insert into okres values('201', 'Dunajská Streda', 'TA');
insert into okres values('811', 'Trebišov', 'KI');
insert into okres values('806', 'Košice - okolie', 'KI');
insert into okres values('602', 'Banská Štiavnica', 'BC');
insert into okres values('601', 'Banská Bystrica', 'BC');
insert into okres values('107', 'Pezinok', 'BL');
insert into okres values('807', 'Michalovce', 'KI');
insert into okres values('401', 'Komárno', 'NI');
insert into okres values('708', 'Sabinov', 'PV');
insert into okres values('402', 'Levice', 'NI');
insert into okres values('704', 'Levoča', 'PV');
insert into okres values('610', 'Veľký Krtíš', 'BC');
insert into okres values('711', 'Stropkov', 'PV');
insert into okres values('204', 'Piešťany', 'TA');
insert into okres values('301', 'Bánovce nad Bebravou', 'TC');
insert into okres values('613', 'Žiar nad Hronom', 'BC');
insert into okres values('809', 'Sobrance', 'KI');
insert into okres values('706', 'Poprad', 'PV');
insert into okres values('304', 'Nové Mesto n.Váhom', 'TC');
insert into okres values('511', 'Žilina', 'ZI');
insert into okres values('709', 'Snina', 'PV');
insert into okres values('407', 'Zlaté Moravce', 'NI');
insert into okres values('506', 'Martin', 'ZI');
insert into okres values('712', 'Svidník', 'PV');
insert into okres values('308', 'Púchov', 'TC');
insert into okres values('505', 'Liptovský Mikuláš', 'ZI');
insert into okres values('108', 'Senec', 'BL');
insert into okres values('508', 'Ružomberok', 'ZI');
insert into okres values('207', 'Trnava', 'TA');
insert into okres values('205', 'Senica', 'TA');
insert into okres values('502', 'Čadca', 'ZI');
insert into okres values('306', 'Považská Bystrica', 'TC');
insert into okres values('302', 'Ilava', 'TC');
insert into okres values('307', 'Prievidza', 'TC');
insert into okres values('203', 'Hlohovec', 'TA');
insert into okres values('106', 'Malacky', 'BL');
insert into okres values('305', 'Partizánske', 'TC');
insert into okres values('105', 'Bratislava V', 'BL');
insert into okres values('104', 'Bratislava IV', 'BL');
insert into okres values('103', 'Bratislava III', 'BL');
insert into okres values('102', 'Bratislava II', 'BL');
insert into okres values('101', 'Bratislava I', 'BL');
insert into okres values('612', 'Žarnovica', 'BC');
insert into okres values('705', 'Medzilaborce', 'PV');
insert into okres values('303', 'Myjava', 'TC');
insert into okres values('607', 'Poltár', 'BC');
insert into okres values('510', 'Tvrdošín', 'ZI');
insert into okres values('206', 'Skalica', 'TA');
insert into okres values('501', 'Bytča', 'ZI');
insert into okres values('503', 'Dolný Kubín', 'ZI');
insert into okres values('605', 'Krupina', 'BC');
insert into okres values('801', 'Gelnica', 'KI');
insert into okres values('710', 'Stará Ľubovňa', 'PV');
insert into okres values('604', 'Detva', 'BC');
insert into okres values('405', 'Šaľa', 'NI');
insert into okres values('504', 'Kysucké Nové Mesto', 'ZI');
insert into okres values('608', 'Revúca', 'BC');
insert into okres values('802', 'Košice I', 'KI');
insert into okres values('803', 'Košice II', 'KI');
insert into okres values('804', 'Košice III', 'KI');
insert into okres values('805', 'Košice IV', 'KI');
insert into okres values('606', 'Lučenec', 'BC');

