insert into typ_ockovania values(1, 'Záškrt');
insert into typ_ockovania values(2, 'Tetanus');
insert into typ_ockovania values(3, 'Čierny kašeľ');
insert into typ_ockovania values(4, 'Vírusový zápal pečene typu B (žltačka typu B)');
insert into typ_ockovania values(5, 'Hemofilové invzívne nákazy');
insert into typ_ockovania values(6, 'Detská obrna');
insert into typ_ockovania values(7, 'Pneumokokové invazívne ochorenia');
insert into typ_ockovania values(8, 'Osýpky');
insert into typ_ockovania values(9, 'Ružienka');
insert into typ_ockovania values(10, 'Mumps');