insert into choroba values(1,1,'Alergia na lepok');
insert into choroba values(2,1,'Alergia na kôrovce a výrobky z kôrovcov');
insert into choroba values(3,1,'Alergia na vajcia a výrobky z vajec');
insert into choroba values(4,1,'Alergia na ryby a výrobky z rýb');
insert into choroba values(5,1,'Alergia na arašidy a výrobky z arašidov');
insert into choroba values(6,1,'Alergia na sójové bôby a výrobky zo sójových bôbov');
insert into choroba values(7,1,'Alergia na mlieko a mliečne výrobky (vrátane laktózy)');
insert into choroba values(8,1,'Alergia na orechy a výrobky z nich');
insert into choroba values(9,1,'Alergia na zeler a výrobky zo zeleru');
insert into choroba values(10,1,'Alergia na horčicu a výrobky z horčice');
insert into choroba values(11,1,'Alergia na sezamové semeno a výrobky zo sezamových semien');
insert into choroba values(12,1,'Alergia na vlčí bôb a výrobky z vlčieho bôbu');
insert into choroba values(13,1,'Alergia na oxid siričitý a siričitany v koncentráciách vyšších ako 10 mg/kg');
insert into choroba values(14,1,'Alergia na mäkkýše a výrobky z mäkkýšov');
insert into choroba values(15,2,'Artérioskleróza');
insert into choroba values(16,2,'Cukrovka');
insert into choroba values(17,2,'Ateroskleróza');
insert into choroba values(18,2,'Infarkt myokardu');
insert into choroba values(19,2,'Angina pectoris');
insert into choroba values(20,2,'Vysoký cholesterol');
insert into choroba values(21,2,'Obezita');
insert into choroba values(22,2,'Únavový syndróm');
insert into choroba values(23,3,'Adrenogenitálny syndróm');
insert into choroba values(24,3,'Achondroplázia');
insert into choroba values(25,3,'Cystická fibróza');
insert into choroba values(26,3,'Downov syndróm');
insert into choroba values(27,3,'Dubowitzov syndróm');
insert into choroba values(28,3,'Familiárna adenomatózna polypóza');
insert into choroba values(29,3,'Huntingtonova choroba');
insert into choroba values(30,3,'Marfanov syndróm');
insert into choroba values(31,3,'Mendelova citlivosť na mykobakteriálne ochorenie');
insert into choroba values(32,3,'Syndróm mačacieho plaču');
insert into choroba values(33,3,'Syndróm XXX');
insert into choroba values(34,3,'Tayov-Sachsov syndróm');
insert into choroba values(35,4,'Abúlia');
insert into choroba values(36,4,'Afektívna porucha');
insert into choroba values(37,4,'Afektívny záchvat');
insert into choroba values(38,4,'Aspergerov syndróm');
insert into choroba values(39,4,'Bipolárna afektívna porucha');
insert into choroba values(40,4,'Cyklotýmia');
insert into choroba values(41,4,'Demencia');
insert into choroba values(42,4,'Demencia s Lewyho telieskami');
insert into choroba values(43,4,'Depersonalizácia');
insert into choroba values(44,4,'Depresia (psychológia)');
insert into choroba values(45,4,'Disociatívna porucha');
insert into choroba values(46,4,'Duševná zaostalosť');
insert into choroba values(47,4,'Dysgrafia');
insert into choroba values(48,4,'Dyslexia');
insert into choroba values(49,4,'Dystýmia');
insert into choroba values(50,4,'Fetišizmus (sex)');
insert into choroba values(51,4,'Hebefrénia');
insert into choroba values(52,4,'Hypománia');
insert into choroba values(53,4,'Hystéria');
insert into choroba values(54,4,'Kleptománia');
insert into choroba values(55,4,'Klinická lykantropia');
insert into choroba values(56,4,'Mánia (psychiatria)');
insert into choroba values(57,4,'Narcizmus');
insert into choroba values(58,4,'Psychická trauma');
insert into choroba values(59,4,'Psychopatia');
insert into choroba values(60,4,'Psychóza');
insert into choroba values(61,4,'Pyrománia');
insert into choroba values(62,4,'Sebapoškodzovanie');
insert into choroba values(63,4,'Schizoafektívna porucha');
insert into choroba values(64,4,'Tanorexia');
insert into choroba values(65,4,'Úzkostné stavy');
insert into choroba values(66,5,'Agorafóbia');
insert into choroba values(67,5,'Akribofóbia');
insert into choroba values(68,5,'Akrofóbia');
insert into choroba values(69,5,'Antropofóbia');
insert into choroba values(70,5,'Arachnofóbia');
insert into choroba values(71,5,'Autofóbia');
insert into choroba values(72,5,'Belemnofóbia');
insert into choroba values(73,5,'Bifóbia');
insert into choroba values(74,5,'Cibofóbia');
insert into choroba values(75,5,'Dysmorfofóbia');
insert into choroba values(76,5,'Ereutofóbia');
insert into choroba values(77,5,'Homofóbia');
insert into choroba values(78,5,'Homosexuálna panika');
insert into choroba values(79,5,'Hoplofóbia');
insert into choroba values(80,5,'Islamofóbia');
insert into choroba values(81,5,'Klaustrofóbia');
insert into choroba values(82,5,'Ofidiofóbia');
insert into choroba values(83,5,'Ofresiofóbia');
insert into choroba values(84,5,'Ochlofóbia');
insert into choroba values(85,5,'Panfóbia');
insert into choroba values(86,5,'Paralipofóbia');
insert into choroba values(87,5,'Patofóbia');
insert into choroba values(88,5,'Pedofóbia');
insert into choroba values(89,5,'Piatok trinásteho');
insert into choroba values(90,5,'Skoptofóbia');
insert into choroba values(91,5,'Sociálna fóbia');
insert into choroba values(92,5,'Stasifóbia');
insert into choroba values(93,5,'Tabofóbia');
insert into choroba values(94,5,'Transfóbia');
insert into choroba values(95,5,'Trypofóbia');
insert into choroba values(96,5,'Xenofóbia');
insert into choroba values(97,6,'Rotavírusová enteritída');
insert into choroba values(98,6,'Detská kolika');
insert into choroba values(99,7,'Hallux valgus');
insert into choroba values(100,8,'Angína');
insert into choroba values(101,8,'Čierny kašeľ');
insert into choroba values(102,8,'Pľúcna embólia');
insert into choroba values(103,8,'Priedušková astma');
insert into choroba values(104,8,'Syndróm spánkového apnoe');
insert into choroba values(105,9,'Absces pľúc');
insert into choroba values(106,9,'Aspirácia (vdýchnutie cudzích telies)');
insert into choroba values(107,9,'Pleurálny výpotok');
insert into choroba values(108,10,'Akromegália');
insert into choroba values(109,11,'Ankylozujúca spondylitída');
insert into choroba values(110,11,'Bakerova cysta');
insert into choroba values(111,11,'Exostóza');
insert into choroba values(112,11,'Kamptodaktýlia');
insert into choroba values(113,11,'Mnohopočetné vrodené exostózy');
insert into choroba values(114,11,'Ostealgia');
insert into choroba values(115,11,'Ploché nohy');
insert into choroba values(116,11,'Rachitída');
insert into choroba values(117,11,'Reumatoidná artritída');
insert into choroba values(118,11,'Osteoporóza');
insert into choroba values(119,12,'Afta');
insert into choroba values(120,12,'Akné');
insert into choroba values(121,12,'Alopécia');
insert into choroba values(122,12,'Atopia');
insert into choroba values(123,12,'Bradavica (kožný výrastok)');
insert into choroba values(124,12,'Ekzém');
insert into choroba values(125,12,'Preležanina');
insert into choroba values(126,12,'Rakovina kože');
insert into choroba values(127,12,'Stria');
insert into choroba values(128,12,'Svrab');
insert into choroba values(129,12,'Kurie oko');
insert into choroba values(130,12,'Mononukleóza');
insert into choroba values(131,12,'Pásový opar');
insert into choroba values(132,12,'Popálenina');
insert into choroba values(133,12,'Popraskané pery');
insert into choroba values(134,12,'Potničky');
insert into choroba values(135,12,'Psoriáza');
insert into choroba values(136,12,'Spáleniny od slnka');
insert into choroba values(137,12,'Starecké škvrny');
insert into choroba values(138,12,'Suchá pokožka');
insert into choroba values(139,13,'Anémia');
insert into choroba values(140,13,'Atypický hemolyticko-uremický syndróm');
insert into choroba values(141,13,'Hemolyticko-uremický syndróm');
insert into choroba values(142,13,'Hodgkinova choroba');
insert into choroba values(143,13,'Methemoglobinémia');
insert into choroba values(144,14,'Balanitída');
insert into choroba values(145,14,'Benígna hyperplázia prostaty');
insert into choroba values(146,14,'Fimóza');
insert into choroba values(147,14,'Frenulotómia');
insert into choroba values(148,14,'Testikulárna mikrolitiáza');
insert into choroba values(149,15,'Alzheimerova choroba');
insert into choroba values(150,15,'Canavanovej choroba');
insert into choroba values(151,15,'Parkinsonova choroba');
insert into choroba values(152,16,'Arteriálna hypertenzia');
insert into choroba values(153,16,'Cievna mozgová príhoda');
insert into choroba values(154,16,'Ischemická choroba srdca');
insert into choroba values(155,16,'Kŕčové žily');
insert into choroba values(156,16,'Ochorenie srdca');
insert into choroba values(157,16,'Srdcové zlyhanie');
insert into choroba values(158,16,'Zúženie krčnej tepny');
insert into choroba values(159,17,'Akútne poškodenie obličiek');
insert into choroba values(160,17,'Albuminúria');
insert into choroba values(161,17,'Glomerulonefritída');
insert into choroba values(162,17,'Tubulointersticiálna nefritída');
insert into choroba values(163,17,'Zlyhanie obličiek');
insert into choroba values(164,17,'Obličkové kamene');
insert into choroba values(165,17,'Problémy s prostatou');
insert into choroba values(166,18,'Ablefária');
insert into choroba values(167,18,'Afakia');
insert into choroba values(168,18,'Ďalekozrakosť');
insert into choroba values(169,18,'Glaukóm - zelený zákal');
insert into choroba values(170,18,'Choroby bielka, rohovky, dúhovky a vráskovca');
insert into choroba values(171,18,'Choroby cievovky a sietnice');
insert into choroba values(172,18,'Choroby mihalníc, slzných orgánov a očnice');
insert into choroba values(173,18,'Choroby oka a jeho adnexov');
insert into choroba values(174,18,'Choroby sklovca a očnej gule');
insert into choroba values(175,18,'Choroby spojovky');
insert into choroba values(176,18,'Choroby šošovky');
insert into choroba values(177,18,'Choroby zrakového nervu a zrakových dráh');
insert into choroba values(178,18,'Iné choroby oka a očných adnexov');
insert into choroba values(179,18,'Krátkozrakosť');
insert into choroba values(180,18,'Lietajúce mušky');
insert into choroba values(181,18,'Poruchy očných svalov, binokulárnych pohybov, akomodácie a refrakcie');
insert into choroba values(182,18,'Poruchy videnia a slepota');
insert into choroba values(183,18,'Sivý zákal');
insert into choroba values(184,18,'Stargardtova choroba');
insert into choroba values(185,18,'Strabizmus');
insert into choroba values(186,18,'Teichopsia');
insert into choroba values(187,18,'Tupozrakosť');
insert into choroba values(188,19,'Análna fisúra');
insert into choroba values(189,19,'Divertikul');
insert into choroba values(190,19,'Hemoroidy');
insert into choroba values(191,19,'Idiopatický črevný zápal');
insert into choroba values(192,19,'Kolorektálny karcinóm');
insert into choroba values(193,19,'Krvácanie do tenkého čreva');
insert into choroba values(194,19,'Meckelov divertikul');
insert into choroba values(195,19,'Polyp');
insert into choroba values(196,19,'Primárna sklerotizujúca cholangitída');
insert into choroba values(197,19,'Rakovina hrubého čreva');
insert into choroba values(198,19,'Ulcerózna kolitída');
insert into choroba values(199,19,'Zápcha');
insert into choroba values(200,19,'Žlčníkové kamene');
insert into choroba values(201,19,'Pálenie záhy');
insert into choroba values(202,20,'Otoskleróza');
insert into choroba values(203,20,'Zápal stredného ucha');
insert into choroba values(204,21,'Cholera');
insert into choroba values(205,21,'Slezinová sneť');
insert into choroba values(206,21,'Škvrnitý týfus');
insert into choroba values(207,21,'Amebóza');
insert into choroba values(208,21,'Bronchopneumónia');
insert into choroba values(209,21,'Detská obrna');
insert into choroba values(210,21,'Dirofilarióza');
insert into choroba values(211,21,'Epidémia eboly v západnej Afrike v rokoch 2013 až 2016');
insert into choroba values(212,21,'Chrípka');
insert into choroba values(213,21,'Jednoduchý opar');
insert into choroba values(214,21,'Kiahne');
insert into choroba values(215,21,'Lymská borelióza');
insert into choroba values(216,21,'Malária');
insert into choroba values(217,21,'Malomocenstvo');
insert into choroba values(218,21,'Nokardióza');
insert into choroba values(219,21,'Opičie kiahne');
insert into choroba values(220,21,'Oportunistická infekcia');
insert into choroba values(221,21,'Osýpky');
insert into choroba values(222,21,'Ovčie kiahne');
insert into choroba values(223,21,'Pneumónia');
insert into choroba values(224,21,'Pseudomembranózna kolitída');
insert into choroba values(225,21,'Ružienka');
insert into choroba values(226,21,'Sepsa');
insert into choroba values(227,21,'Spavá choroba');
insert into choroba values(228,21,'Syndróm získanej imunitnej nedostatočnosti');
insert into choroba values(229,21,'Toxoplazmóza');
insert into choroba values(230,21,'Tuberkulóza');
insert into choroba values(231,21,'Vtáčia chrípka');
insert into choroba values(232,21,'Zápal príušných žliaz');
insert into choroba values(233,22,'Zhubné nádory pery, ústnej dutiny a hltana');
insert into choroba values(234,22,'Zhubné nádory tráviacich orgánov');
insert into choroba values(235,22,'Zhubné nádory dýchacích a vnútrohrudníkových orgánov');
insert into choroba values(236,22,'Zhubné nádory kostí a kĺbovej chrupky');
insert into choroba values(237,22,'Melanóm a iné zhubné nádory kože');
insert into choroba values(238,22,'Zhubné nádory mezotelu a mäkkého tkaniva');
insert into choroba values(239,22,'Zhubné nádory prsníka');
insert into choroba values(240,22,'Zhubné nádory ženských pohlavných orgánov');
insert into choroba values(241,22,'Zhubné nádory mužských pohlavných orgánov');
insert into choroba values(242,22,'Zhubné nádory močovej sústavy');
insert into choroba values(243,22,'Zhubné nádory oka, mozgu a iných častí centrálnej nervovej sústavy');
insert into choroba values(244,22,'Zhubné nádory štítnej žľazy a iných žliaz s vnútorným vylučovaním');
insert into choroba values(245,22,'Zhubné nádory na nepresne určených, sekundárnych a bližšie neurčených miestach');
insert into choroba values(246,22,'Zhubné nádory pôvodom alebo s predpokladaným pôvodom z lymfatického, hemopoetického a príbuzného tkaniva');
insert into choroba values(247,22,'Zhubné nádory mnohopočetné na viacerých nezávislých primárnych miestach');
insert into choroba values(248,22,'Karcinómy in situ');
insert into choroba values(249,22,'Nezhubné nádory');
insert into choroba values(250,22,'Nádory s neurčitým alebo neznámym správaním');
insert into choroba values(251,22,'Zhubný nádor jazyka presahujúci viaceré oblasti');
insert into choroba values(252,22,'Zhubný nádor veľkých slinných žliaz presahujúci viaceré oblasti');
insert into choroba values(253,22,'Zhubný nádor pery, ústnej dutiny a hltana presahujúci viaceré oblasti');
insert into choroba values(254,22,'Zhubný nádor rekta, anusu a análneho kanála presahujúci viaceré oblasti');
insert into choroba values(255,22,'Zhubný nádor žlčových ciest presahujúci viaceré oblasti');
insert into choroba values(256,22,'Zhubný nádor tráviacej sústavy presahujúci viaceré oblasti');
insert into choroba values(257,22,'Zhubný nádor dýchacích a vnútrohrudníkových orgánov presahujúci viaceré oblasti');
insert into choroba values(258,22,'Zhubný nádor kosti a kĺbovej chrupky presahujúci viaceré oblasti');
insert into choroba values(259,22,'Zhubný nádor spojivového a mäkkého tkaniva presahujúci viaceré oblasti');
insert into choroba values(260,22,'Zhubný nádor ženských pohlavných orgánov presahujúci viaceré oblasti');
insert into choroba values(261,22,'Zhubný nádor mužských pohlavných orgánov presahujúci viaceré oblasti');
insert into choroba values(262,22,'Zhubný nádor močových orgánov presahujúci viaceré oblasti');
insert into choroba values(263,22,'Zhubný nádor mozgu a iných časti centrálnej nervovej sústavy presahujúci viaceré oblasti');
insert into choroba values(264,23,'Autizmus');
insert into choroba values(265,23,'Afázia');
insert into choroba values(266,23,'Amúzia');
insert into choroba values(267,23,'Areflexia');
insert into choroba values(268,23,'Besnota');
insert into choroba values(269,23,'Epilepsia');
insert into choroba values(270,23,'Misophonia');
insert into choroba values(271,23,'Prosopagnózia');
insert into choroba values(272,23,'Skleróza multiplex');
insert into choroba values(273,23,'Syndróm nepokojných nôh');
insert into choroba values(274,23,'Tik');
insert into choroba values(275,23,'Tinitus');
insert into choroba values(276,24,'Kvapavka');
insert into choroba values(277,24,'Ľudský papilomavírus');
insert into choroba values(278,24,'Syfilis');
insert into choroba values(279,24,'Vírus ľudskej imunitnej nedostatočnosti');
insert into choroba values(280,24,'Zápal krčka maternice');
insert into choroba values(281,24,'Menštruačné ťažkosti');
insert into choroba values(282,24,'Neplodnosť');
insert into choroba values(283,24,'Nepravidelná menštruácia');
insert into choroba values(284,24,'Vaginálne problémy');
insert into choroba values(285,25,'Bulímia');
insert into choroba values(286,25,'Kachexia');
insert into choroba values(287,25,'Mentálna anorexia');
insert into choroba values(288,25,'Ortorexia nervosa');
insert into choroba values(289,25,'Podvýživa');
insert into choroba values(290,26,'Paranoja');
insert into choroba values(291,26,'Amfetamínová psychóza');
insert into choroba values(292,26,'Reaktívna psychóza');
insert into choroba values(293,27,'Alkoholizmus');
insert into choroba values(294,27,'Drogy');
insert into choroba values(295,27,'Fajčenie');
