insert into typ_lekara values(1,'Akupunkturista');
insert into typ_lekara values(2,'Alergológ a imunológ');
insert into typ_lekara values(3,'Algeziológ');
insert into typ_lekara values(4,'Anestéziológ');
insert into typ_lekara values(5,'Angiochirurg');
insert into typ_lekara values(6,'Angiológ');
insert into typ_lekara values(7,'Audiológ');
insert into typ_lekara values(8,'Chirurg');
insert into typ_lekara values(9,'Cytológ');
insert into typ_lekara values(10,'Dermatológ - kožný lekár');
insert into typ_lekara values(11,'Dermatovenerológ');
insert into typ_lekara values(12,'Diabetológ');
insert into typ_lekara values(13,'Diagnostik');
insert into typ_lekara values(14,'Endokrinológ');
insert into typ_lekara values(15,'Epidemiológ');
insert into typ_lekara values(16,'Foniatrik');
insert into typ_lekara values(17,'Ftizeológ');
insert into typ_lekara values(18,'Fyzioterapeut - nelekársky odbor');
insert into typ_lekara values(19,'Gastroenterológ');
insert into typ_lekara values(20,'Genetik');
insert into typ_lekara values(21,'Geriater');
insert into typ_lekara values(22,'Gerontológ');
insert into typ_lekara values(23,'Gynekológ - Reprodukčná medicína');
insert into typ_lekara values(24,'Gynekológ a pôrodník');
insert into typ_lekara values(25,'Hematológ');
insert into typ_lekara values(26,'Hepatológ');
insert into typ_lekara values(27,'Histológ');
insert into typ_lekara values(28,'Hlavný odborník MZ SR');
insert into typ_lekara values(29,'Homeopat');
insert into typ_lekara values(30,'Hygienik');
insert into typ_lekara values(31,'Hyperbarická medicína - špecialista');
insert into typ_lekara values(32,'Infektológ');
insert into typ_lekara values(33,'Internista');
insert into typ_lekara values(34,'Kardiochirurg');
insert into typ_lekara values(35,'Kardiológ');
insert into typ_lekara values(36,'Klinický a dopravný psychológ');
insert into typ_lekara values(37,'Klinický biochemik');
insert into typ_lekara values(38,'Logopéd');
insert into typ_lekara values(39,'Mamológ');
insert into typ_lekara values(40,'Mikrobiológ');
insert into typ_lekara values(41,'Nefrológ');
insert into typ_lekara values(42,'Neonatológ');
insert into typ_lekara values(43,'Neurochirurg');
insert into typ_lekara values(44,'Neurológ');
insert into typ_lekara values(45,'Neurológ - centrum SM');
insert into typ_lekara values(46,'Nozológ');
insert into typ_lekara values(47,'Oftalmológ - očný lekár');
insert into typ_lekara values(48,'Onkológ');
insert into typ_lekara values(49,'Ortopéd');
insert into typ_lekara values(50,'Ošetrovatelstvo - zdravotnícky odbor');
insert into typ_lekara values(51,'Otorinolaryngológ');
insert into typ_lekara values(52,'Patológ');
insert into typ_lekara values(53,'Pediater');
insert into typ_lekara values(54,'Plastický chirurg');
insert into typ_lekara values(55,'Pneumológ');
insert into typ_lekara values(56,'Praktický lekár');
insert into typ_lekara values(57,'Psychiater');
insert into typ_lekara values(58,'Psychológ');
insert into typ_lekara values(59,'Radiológ');
insert into typ_lekara values(60,'Rádioterapeut');
insert into typ_lekara values(61,'Rehabilitačný lekár');
insert into typ_lekara values(62,'Reumatológ');
insert into typ_lekara values(63,'Sexuológ');
insert into typ_lekara values(64,'Skleróza Multiplex – špecialista');
insert into typ_lekara values(65,'Stomatológ - zubný lekár');
insert into typ_lekara values(66,'Toxikológ');
insert into typ_lekara values(67,'Traumatológ');
insert into typ_lekara values(68,'Urológ');
insert into typ_lekara values(69,'Venerológ');
insert into typ_lekara values(70,'Všeobecný lekár pre deti a dorast');
insert into typ_lekara values(71,'Všeobecný lekár pre dospelých');
