insert into typ_oddelenia values(1,'Alergologické oddelenie');
insert into typ_oddelenia values(2,'Anesteziologické oddelenie');
insert into typ_oddelenia values(3,'Angiologické oddelenie');
insert into typ_oddelenia values(4,'ARO');
insert into typ_oddelenia values(5,'Detské oddelenie');
insert into typ_oddelenia values(6,'Endokrinologické oddelenie');
insert into typ_oddelenia values(7,'Fyziatricko-rehabilitačné oddelenie');
insert into typ_oddelenia values(8,'Geriatrické oddelenie');
insert into typ_oddelenia values(9,'Gynekologicko-pôrodnícke oddelenie');
insert into typ_oddelenia values(10,'Hematologické oddelenie');
insert into typ_oddelenia values(11,'Chirurgické oddelenie');
insert into typ_oddelenia values(12,'Chirurgicko-traumatologické oddelenie');
insert into typ_oddelenia values(13,'Infekčné oddelenie');
insert into typ_oddelenia values(14,'Interné oddelenie');
insert into typ_oddelenia values(15,'JIP');
insert into typ_oddelenia values(16,'Kožné oddelenie');
insert into typ_oddelenia values(17,'Nefrologické oddelenie');
insert into typ_oddelenia values(18,'Neurochirurgické oddelenie');
insert into typ_oddelenia values(19,'Neurologické oddelenie');
insert into typ_oddelenia values(20,'Novorodenecké oddelenie');
insert into typ_oddelenia values(21,'Očné oddelenie');
insert into typ_oddelenia values(22,'Oddelenie cievnej chirurgie');
insert into typ_oddelenia values(23,'Oddelenie dlhodobo chorých');
insert into typ_oddelenia values(24,'Oddelenie gastroenterológie');
insert into typ_oddelenia values(25,'Oddelenie kardiológie');
insert into typ_oddelenia values(26,'Oddelenie liečebnej výživy a stravovania');
insert into typ_oddelenia values(27,'Oddelenie plastickej chirurgie');
insert into typ_oddelenia values(28,'Oddelenie pneumológie a ftizeológie');
insert into typ_oddelenia values(29,'Oddelenie telovýchovného lekárstva');
insert into typ_oddelenia values(30,'Oddelenie úrazovej chirurgie');
insert into typ_oddelenia values(31,'Oddelenie urológie');
insert into typ_oddelenia values(32,'Oddelenie ústnej, čeľustnej a tvárovej chirurgie');
insert into typ_oddelenia values(33,'Onkologické oddelenie');
insert into typ_oddelenia values(34,'Ortopedické oddelenie');
insert into typ_oddelenia values(35,'Otorinolaryngologické oddelenie');
insert into typ_oddelenia values(36,'Pľúcne oddelenie');
insert into typ_oddelenia values(37,'Psychiatrické oddelenie');
insert into typ_oddelenia values(38,'Rádiodiagnostické oddelenie');
insert into typ_oddelenia values(39,'Rádiologické oddelenie');
insert into typ_oddelenia values(40,'Úrazové oddelenie');
insert into typ_oddelenia values(41,'Urologické oddelenie');